spring.application.name=backend
# ==========================================
# InstantDRS - Database Configuration
# ==========================================

# MySQL Database
spring.datasource.url=jdbc:mysql://localhost:3306/instant_drs?useSSL=false&serverTimezone=Asia/Kolkata&allowPublicKeyRetrieval=true

spring.datasource.username=root

spring.datasource.password=${DB_PASSWORD}
# Automatically create/update tables during development
spring.jpa.hibernate.ddl-auto=update

# Show SQL queries in console
spring.jpa.show-sql=true

# Format SQL queries
spring.jpa.properties.hibernate.format_sql=true

# ==========================================
# Server
# ==========================================

server.port=8080

# ==========================================
# InstantDRS - Video Engine Configuration
# ==========================================
instantdrs.video-engine.python=C:/Users/Shivansh Tiwari/Desktop/InstantDRS/video-engine/tool3-sports-ball-tracking/.venv/Scripts/python.exe
instantdrs.video-engine.pipeline=C:/Users/Shivansh Tiwari/Desktop/InstantDRS/video-engine/pipeline/run_pipeline.py
instantdrs.video-engine.fast-pipeline=C:/Users/Shivansh Tiwari/Desktop/InstantDRS/video-engine/pipeline/fast_drs_pipeline.py
instantdrs.video-engine.use-fast-pipeline=true
instantdrs.storage.original-dir=storage/original/
instantdrs.storage.processed-dir=storage/processed/

spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB